### ISSUE TITLE
Wrong commands in readme

### ISSUE THREAD

**Issue by adman234** [Silleellie/dnd-bedtime-sync#11]
Sorry, I don't know how to use github to recommend this fix but there is a typo in the readme using the old version of this app. The commands to run via ADB should be:

adb shell pm grant it.silleellie.dndsync android.permission.WRITE_SECURE_SETTINGS

adb shell cmd notification allow_listener it.silleellie.dndsync/it.silleellie.dndsync.DNDNotificationService

**Comment by Silleellie** [comment]
Hey there, thank you for your input! I don't have a samsung galaxy watch to test it anymore, but last month I installed this into the galaxy watch of my mother and I copy-pasted the instructions into adb. Everything was working, so I need to double check this before updating the README.

In any case I will leave this open so that, if someone else has this problem, can solve it checking this issue and maybe comment in support of it, then I'll know I need to fix the readme

Thank you!

**Comment by B14NK17** [comment]
those commands worked for me! the ones in the readme did not

**Comment by Silleellie** [comment]
Sorry both @adman234 and @B14NK17 for the ping, but as I went to update the README, I just found out that the commands you are telling me to update already point to the correct version of this app. I don't know which version of this repository you are seeing haha. This is a screenshot of the relevant part of the readme you are telling me to change:
![image](https://github.com/user-attachments/assets/679e37e3-2ee8-41a7-b1cb-72540e137e78)


And this is the direct link to the README in the [master branch](https://github.com/Silleellie/dnd-bedtime-sync/blob/master/README.md). Can you confirm you correctly see the updated commands? If not, could you link me what readme you are seeing?

**Comment by B14NK17** [comment]
weird, they seem to be the same for me too right now. I closed the command line so I can't see what I did wrong initially. I don't really use github but maybe I clicked an old link on reddit to see something outdated?

**Comment by B14NK17** [comment]
also I had an issue where I somehow got multiple adb devices connected which gave some adb error when trying to run the perm commands - the available devices looked like they appeared from the `adb pair` and `adb connect` commands. chatgpt told me to start commands with `adb -s 192.168.0.100:5555` to specify the watch which worked

**Comment by adman234** [comment]
The readme has changed, the previous readme of this project specified using these commands:

adb shell cmd notification allow_listener de.rhaeus.dndsync/
de.rhaeus.dndsync.DNDNotificationService

I'm not sure how the readme updated, but it seems to somehow be related to this project being a branch of the rhaeus project. I'm not a programmer so I have no idea, but whatever the reason, it seems to be fixed now.
