### ISSUE TITLE
Toggle to enable dnd with bedtime

### ISSUE THREAD

**Issue by provalinf** [Silleellie/dnd-bedtime-sync#2]
Hi Antonio,

I wanted to know if you could add a togglebutton to switch the watch to bedtime mode if the trigger to activate the dnd is received. 
Because a lot of us have a problem on xiaomi phones (under miui 13 and miui 14 and maybe even hyperos) is that we don't have bedtime mode on the mobile. So since we can program the dnd on the mobile, if it could activate the watch's bedtime mode at the same time, that would be great!

Happy new year!

**Comment by Silleellie** [comment]
Happy New Year to you too!
So, if I understand correctly, whenever on the phone DND is enabled, you would want to enable on the watch both DND and Bedtime mode?

**Comment by provalinf** [comment]
Yes, that's exactly it, because as indicated, there is no bedtime mode on the Xiaomi.

The old version which used the accessibility mode (with the reliability that we know) directly activated the mode that we put in the quick access I believe on the 1st line in the middle and therefore by putting the bedtime icon  , the dnd was activated at the same time.

**Comment by Silleellie** [comment]
I see. Sadly I'm a bit busy at the moment, but it should be fairly easy to implement. I hope to bring this functionality during this month, as soon as I'm a bit more free! Thank you for the issue as it is an additional functionality which could be useful to many people :)

**Comment by Silleellie** [comment]
I'm actively developing this functionality. @provalinf Expect it to drop in the next few days!

**Comment by Silleellie** [comment]
Hey man, I added the functionality you requested, along with some small changes. You can find the new version [here](https://github.com/Silleellie/dnd-bedtime-sync/releases/tag/v2.0.0). Remember to uninstall previous version of both apps and follow the instruction stated in the README!

I will close this issue now, feel free to reopen it if something's wrong!

**Comment by provalinf** [comment]
Hey @Silleellie,
Everything works perfectly, it's really cool to have made the feature! 
Thanks a lot!!
