### ISSUE TITLE
AlarmSync with stock Google Clock

### ISSUE THREAD

**Issue by martenumberto** [Silleellie/dnd-bedtime-sync#5]
Hey!

Do you think it could be possible to Sync the Alarms from the Google Clock like the setup of a PW2 and a Pixel Phone?
Sadly this function is only available on Google Phones.

**Comment by Silleellie** [comment]
What do you mean sync the alarms? There's the "clock" app available in the play store both for the watch and the phone which does that, but I don't understand how this project is related to it 😁

**Comment by Silleellie** [comment]
I'll close this issue for inactivity! If you need more help, feel free to reopen it!
