### ISSUE TITLE
Phone to watch sync no longer works after OS update

### ISSUE THREAD

**Issue by SonOfTheKingdom** [Silleellie/dnd-bedtime-sync#6]
Watch-to-phone sync works as usual but phone-to-watch sync no longer works. Was working like a charm before OS update. Reinstalled both apps without success. Using a Redmi Note 11 Pro+ now with HyperOS and a Watch5 Pro.

**Comment by Silleellie** [comment]
Sorry for the late reply, strangely I did not get any notification for this issue :(

In any case, I'm not able to replicate this issue. What OS update are you referring to? Phone OS update or Wear OS update?

**Comment by KatieCakezz** [comment]
Hey, I'm not able to sync dnd in either direction. I'd love some help if possible!

dndsync watch "permission access granted" and "accessibility connected"
dndsync android app permission granted. 

all switches are toggled on except for bedtime mode on dnd. 

Using an s24 ultra one 6.1 and OnePlus watch 2 os v6.0 android 13

a few posts on r/onepluswatch2 lead me here with those who've tried it saying it works.

**Comment by Silleellie** [comment]
Closed due to no update
