### ISSUE TITLE
No Issues - Just confirmation it works with PXL 9Pro XL + Galaxy Watch 6 Classic

### ISSUE THREAD

**Issue by Tronnic** [Silleellie/dnd-bedtime-sync#9]
Hey, as the title says. 

Just wanted to tell the dev that this works perfectly for the Google Pixel 9 Pro XL and the Samsung Galaxy Watch 6 Classic. 

Thanks again for the amazing work :-) 

https://github.com/user-attachments/assets/775ae1fb-ceff-4bad-b71e-7c3220916e1b

**Comment by Silleellie** [comment]
Thank you for the valuable feedback!! I'll try to gather all the feedbacks received on which devices this project is confirmed to work and update the README!
